executables:
  colmap: C:/Users/erkab/Desktop/Projects/Thesis/COLMAP/COLMAP.bat
  densify: C:/vcpkg/installed/x64-windows/tools/openmvs/DensifyPointCloud.exe
  interface_colmap: C:/vcpkg/installed/x64-windows/tools/openmvs/InterfaceCOLMAP.exe
  reconstruct_mesh: C:/vcpkg/installed/x64-windows/tools/openmvs/ReconstructMesh.exe
  refine_mesh: C:/vcpkg/installed/x64-windows/tools/openmvs/RefineMesh.exe
  texture_mesh: C:/vcpkg/installed/x64-windows/tools/openmvs/TextureMesh.exe
paths:
  input_dir: data/input
  workspace_dir: data/workspace
settings:
  matching_method: sequential
  run_refine: false
  run_texture: false
  seq_overlap: 20
  use_gpu: true
  use_ml_features: true
  vocab_tree_path: ''
